services:
  configurator:
    environment:
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
    depends_on:
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy

  redis-cache:
    image: redis:8.6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5

  redis-queue:
    image: redis:8.6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-queue-data:/data

volumes:
  redis-queue-data:
