from datetime import datetime, timezone


SYSTEM_FIELDNAMES = {"name", "owner", "creation", "modified", "modified_by", "docstatus", "naming_series"}
SYSTEM_FIELD_TYPES = {"Section Break", "Column Break", "Tab Break", "HTML", "Button", "Image", "Fold", "Heading"}
DERIVED_REASON_MARKERS = ("context", "conversation", "current page")


class ReviewBuilderService:
    def build_creation_review(self, doctype, data=None, fields=None, supplied_data=None, defaults_applied=None, context=None, user=None):
        data = data or {}
        fields = fields or []
        supplied_data = supplied_data or {}
        defaults_applied = defaults_applied or []
        field_map = {field.get("fieldname"): field for field in fields if field.get("fieldname")}

        default_fieldnames = {item.get("fieldname") for item in defaults_applied if item.get("fieldname")}
        derived_defaults = [item for item in defaults_applied if is_derived_default(item)]
        derived_fieldnames = {item.get("fieldname") for item in derived_defaults if item.get("fieldname")}

        captured = []
        for fieldname, value in supplied_data.items():
            if value in (None, "", []):
                continue
            field = field_map.get(fieldname, {"fieldname": fieldname})
            if not is_reviewable_field(field):
                continue
            captured.append(review_row(field, value, data=data))

        default_rows = [
            review_row(field_map.get(item.get("fieldname"), {"fieldname": item.get("fieldname"), "label": item.get("label")}), item.get("value"), reason=item.get("reason"), data=data)
            for item in defaults_applied
            if item.get("fieldname") not in derived_fieldnames and item.get("fieldname") not in SYSTEM_FIELDNAMES
        ]
        derived_rows = [
            review_row(field_map.get(item.get("fieldname"), {"fieldname": item.get("fieldname"), "label": item.get("label")}), item.get("value"), reason=item.get("reason"), data=data)
            for item in derived_defaults
            if item.get("fieldname") not in SYSTEM_FIELDNAMES
        ]

        for fieldname, value in data.items():
            if value in (None, "", []) or fieldname in supplied_data or fieldname in default_fieldnames:
                continue
            field = field_map.get(fieldname, {"fieldname": fieldname})
            if not is_reviewable_field(field):
                continue
            derived_rows.append(review_row(field, value, reason="Derived from request or current context.", data=data))

        return {
            "doctype": doctype,
            "captured_details": captured,
            "default_values": default_rows,
            "derived_values": dedupe_rows(derived_rows),
            "system_generated_values": self.system_generated_rows(doctype, fields, user=user),
            "editable_fields": editable_fields(fields),
            "context": context or {},
        }

    def build_update_review(self, doctype, docname=None, current=None, changes=None, fields=None, context=None, user=None):
        current = current or {}
        changes = changes or {}
        fields = fields or []
        field_map = {field.get("fieldname"): field for field in fields if field.get("fieldname")}

        change_rows = []
        for fieldname, new_value in changes.items():
            if new_value in (None, "", []):
                continue
            field = field_map.get(fieldname, {"fieldname": fieldname})
            if not is_reviewable_field(field):
                continue
            change_rows.append(
                {
                    "fieldname": fieldname,
                    "label": field_label(field),
                    "current_value": current.get(fieldname),
                    "new_value": new_value,
                }
            )

        return {
            "doctype": doctype,
            "docname": docname,
            "change_rows": change_rows,
            "editable_fields": editable_fields(fields),
            "system_generated_values": self.update_system_rows(user=user),
            "context": context or {},
        }

    def system_generated_rows(self, doctype, fields=None, user=None):
        fieldnames = {field.get("fieldname") for field in fields or [] if field.get("fieldname")}
        rows = [
            {"label": "Owner", "value": user or "Current User", "fieldname": "owner"},
            {"label": "Creation Time", "value": "Current Timestamp", "fieldname": "creation"},
            {"label": "Modified Time", "value": "Current Timestamp", "fieldname": "modified"},
            {"label": "Document Status", "value": "Draft", "fieldname": "docstatus"},
            {"label": "Document Name", "value": "Generated by Talisma OneCampus", "fieldname": "name"},
        ]
        if "naming_series" in fieldnames:
            rows.append({"label": "Naming Series", "value": "Applied by Talisma OneCampus", "fieldname": "naming_series"})
        return rows

    def update_system_rows(self, user=None):
        return [
            {"label": "Modified By", "value": user or "Current User", "fieldname": "modified_by"},
            {"label": "Modified Time", "value": "Current Timestamp", "fieldname": "modified"},
        ]


def format_creation_review_card(prepared, title=None):
    doctype = friendly_doctype(prepared.get("doctype"))
    review = prepared.get("review") or {}
    dependencies = prepared.get("missing_dependencies") or prepared.get("missing_link_dependencies") or []
    lines = [
        title or f"{doctype} Creation Review",
        "I prepared this record for review.",
        "",
    ]
    append_section(lines, "Captured Details", review.get("captured_details"), empty="- No user-supplied values were detected yet.")
    append_section(lines, "Default Configuration", review.get("default_values"), empty="- No business defaults were applied.")
    append_section(lines, "System Generated Values", review.get("system_generated_values"), empty="- Talisma OneCampus will apply standard system values.")
    append_section(lines, "Derived Values", review.get("derived_values"), empty="- No values were derived from context.")

    missing = prepared.get("missing_fields") or []
    if missing:
        lines.extend(["", "Next Required Detail"])
        next_field = prepared.get("next_missing_field") or {}
        lines.append(f"- {next_field.get('label') or missing[0]}")
        remaining = max(len(missing) - 1, 0)
        if remaining:
            lines.append(f"- {remaining} more detail(s) will follow one by one.")

    if dependencies:
        lines.extend(["", "Missing Dependencies"])
        for dependency in dependencies:
            lines.append(f"- {dependency.get('target_doctype')} {dependency.get('value')} is missing.")

    lines.extend(["", "Current Status"])
    if prepared.get("ready") and dependencies:
        lines.append(f"- {doctype} creation is paused until required dependencies are available.")
        lines.append("- No Talisma OneCampus data has been changed.")
    elif prepared.get("ready"):
        lines.append("- Ready to create after your confirmation.")
        lines.append("- Talisma OneCampus permissions and validation rules will still be applied.")
    else:
        lines.append(f"- No Talisma OneCampus {doctype} has been created yet.")
        lines.append(f"- Please provide {question_label(prepared)}.")

    return "\n".join(lines)


def append_nested_review(lines, review):
    doctype = friendly_doctype(review.get("doctype"))
    lines.extend(["", f"{doctype} Creation Review"])
    append_section(lines, "Captured Details", review.get("captured_details"), empty="- No user-supplied values were detected yet.")
    append_section(lines, "Default Configuration", review.get("default_values"), empty="- No business defaults were applied.")
    append_section(lines, "System Generated Values", review.get("system_generated_values"), empty="- Talisma OneCampus will apply standard system values.")
    derived = review.get("derived_values") or []
    if derived:
        append_section(lines, "Derived Values", derived)


def format_update_review_card(prepared):
    doctype = friendly_doctype(prepared.get("doctype"))
    docname = prepared.get("docname") or "Not selected"
    review = prepared.get("review") or {}
    dependencies = prepared.get("missing_dependencies") or prepared.get("missing_link_dependencies") or []

    lines = [
        f"{doctype} Update Review",
        "I prepared this update for review.",
        "",
        "Record",
        f"- {doctype}: {docname}",
        "",
        "Proposed Changes",
    ]

    changes = review.get("change_rows") or []
    if changes:
        for row in changes:
            lines.append(f"- {row.get('label')}: {format_value(row.get('current_value'))} -> {format_value(row.get('new_value'))}")
    else:
        lines.append("- No update values were captured yet.")

    if dependencies:
        lines.extend(["", "Missing Dependencies"])
        for dependency in dependencies:
            lines.append(f"- {dependency.get('target_doctype')} {dependency.get('value')} is missing.")

    impact = prepared.get("impact") or []
    if impact:
        lines.extend(["", "Business Impact"])
        lines.extend(f"- {item}" for item in impact)

    validation_issues = prepared.get("validation_issues") or []
    lines.extend(["", "Validation"])
    if validation_issues:
        for issue in validation_issues[:6]:
            lines.append(f"- {issue.get('message') or issue.get('fieldname') or 'Talisma OneCampus validation did not pass.'}")
    elif prepared.get("ready"):
        lines.append("- Ready to update after your confirmation.")
    else:
        lines.append("- More information is required before this can be updated.")

    system_rows = review.get("system_generated_values") or []
    append_section(lines, "System Generated Values", system_rows, empty="- Talisma OneCampus will apply standard update metadata.")

    lines.extend(["Current Status"])
    if prepared.get("ready") and dependencies:
        lines.append(f"- {doctype} update is paused until required dependencies are available.")
        lines.append("- No Talisma OneCampus data has been changed.")
    elif prepared.get("ready"):
        lines.append("- Ready to update after your confirmation.")
        lines.append("- Talisma OneCampus permissions and validation rules will still be applied.")
    else:
        lines.append("- No Talisma OneCampus data has been changed.")
        lines.append(f"- Please provide {question_label(prepared)}.")

    return "\n".join(lines)


def append_section(lines, title, rows, empty=None):
    lines.append(title)
    if rows:
        for row in rows:
            value = format_value(row.get("value"))
            reason = row.get("reason")
            suffix = f" ({reason})" if reason and "context" in str(reason).lower() else ""
            lines.append(f"- {row.get('label')}: {value}{suffix}")
    elif empty:
        lines.append(empty)
    lines.append("")


def review_row(field, value, reason=None, data=None):
    return {
        "fieldname": (field or {}).get("fieldname"),
        "label": display_field_label(field, data=data),
        "value": value,
        "reason": reason,
    }


def editable_fields(fields):
    result = []
    for field in fields or []:
        if not is_reviewable_field(field) or field.get("read_only"):
            continue
        result.append(
            {
                "fieldname": field.get("fieldname"),
                "label": field_label(field),
                "fieldtype": field.get("fieldtype"),
                "options": field.get("options"),
            }
        )
    return result


def is_reviewable_field(field):
    fieldname = (field or {}).get("fieldname")
    if not fieldname or fieldname in SYSTEM_FIELDNAMES:
        return False
    if (field or {}).get("hidden"):
        return False
    if (field or {}).get("fieldtype") in SYSTEM_FIELD_TYPES:
        return False
    return True


def is_derived_default(item):
    reason = str((item or {}).get("reason") or "").lower()
    return any(marker in reason for marker in DERIVED_REASON_MARKERS)


def dedupe_rows(rows):
    seen = set()
    result = []
    for row in rows or []:
        key = (row.get("fieldname"), row.get("value"))
        if key in seen:
            continue
        seen.add(key)
        result.append(row)
    return result


def field_label(field):
    return (field or {}).get("label") or str((field or {}).get("fieldname") or "Field").replace("_", " ").title()


def display_field_label(field, data=None):
    if (field or {}).get("fieldtype") == "Dynamic Link":
        target = dynamic_link_target(field, data or {})
        if target:
            return target
    return field_label(field)


def dynamic_link_target(field, data):
    controller = (field or {}).get("options")
    return (data or {}).get(controller) or (field or {}).get("target_doctype") or ((field or {}).get("component") or {}).get("target_doctype")


def format_value(value):
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if value in (None, ""):
        return "Blank"
    if isinstance(value, list):
        labels = []
        for item in value:
            if isinstance(item, dict):
                preferred = next((item.get(key) for key in ("student_name", "course", "course_category", "requirement_name", "item_code", "name") if item.get(key) not in (None, "", [])), None)
                labels.append(str(preferred) if preferred is not None else next((str(val) for val in item.values() if val not in (None, "", [])), ""))
            elif item not in (None, "", []):
                labels.append(str(item))
        return ", ".join(label for label in labels if label) or "None"
    if isinstance(value, datetime):
        return value.astimezone(timezone.utc).isoformat()
    return value


def friendly_doctype(doctype):
    return str(doctype or "Record").removeprefix("Talisma ")


def question_label(prepared):
    field = prepared.get("next_missing_field") or {}
    label = field.get("label") or ((prepared.get("missing_fields") or ["the required detail"])[0])
    fieldtype = field.get("fieldtype")
    if field.get("fieldname") == "items":
        return f'{label}, for example "SKU008 qty 2"'
    if fieldtype == "Date":
        return f'{label}, for example "2026-07-03"'
    return label
