[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wingman_ai"
authors = [
    { name = "Talisma Wingman Team" }
]
description = "AI work partner for Talisma OneCampus"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]

[tool.bench.dev-dependencies]
