ARG FRAPPE_BRANCH=v16.25.0
ARG FRAPPE_IMAGE_PREFIX=frappe

FROM ${FRAPPE_IMAGE_PREFIX}/build:${FRAPPE_BRANCH} AS builder

ARG FRAPPE_BRANCH=v16.25.0
ARG FRAPPE_PATH=https://github.com/frappe/frappe.git
ARG ERPNEXT_COMMIT=d1d3b241ae7bc21d18cf830a4bacd568e21a2a19
ARG EDUCATION_COMMIT=ab3794da21dfd145825293319f89c746811a15cd
ARG CACHE_BUST=""

ENV YARN_NETWORK_TIMEOUT=600000

USER frappe

RUN --mount=type=secret,id=apps_json,target=/opt/frappe/apps.json,uid=1000,gid=1000 \
  : "${CACHE_BUST}" && \
  bench init --apps_path=/opt/frappe/apps.json \
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=${FRAPPE_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

RUN git -C apps/erpnext fetch origin ${ERPNEXT_COMMIT} && \
  git -C apps/erpnext checkout --detach ${ERPNEXT_COMMIT} && \
  test "$(git -C apps/erpnext rev-parse HEAD)" = "${ERPNEXT_COMMIT}" && \
  git -C apps/education fetch origin ${EDUCATION_COMMIT} && \
  git -C apps/education checkout --detach ${EDUCATION_COMMIT} && \
  test "$(git -C apps/education rev-parse HEAD)" = "${EDUCATION_COMMIT}"

RUN bench setup requirements

RUN bench build --production && \
  echo "{}" > sites/common_site_config.json

RUN find apps -mindepth 1 -path "*/.git" -print0 | xargs -0 -r rm -fr

FROM ${FRAPPE_IMAGE_PREFIX}/base:${FRAPPE_BRANCH} AS backend

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

RUN cp -r /home/frappe/frappe-bench/sites/assets /home/frappe/frappe-bench/assets && \
  rm -rf /home/frappe/frappe-bench/sites/assets

VOLUME [ "/home/frappe/frappe-bench/sites", "/home/frappe/frappe-bench/logs" ]

USER root

COPY resources/core/main-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/entrypoint.sh && chmod 755 /usr/local/bin/entrypoint.sh

COPY resources/core/start.sh /usr/local/bin/start.sh
RUN sed -i 's/\r$//' /usr/local/bin/start.sh && chmod 755 /usr/local/bin/start.sh

USER frappe
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["start.sh"]
